### ISSUE TITLE
ExcelWorkbook.get_sheet_name_list() not working

### ISSUE THREAD

**Issue by whiteshampoo** [LaoDie1/godot-excel-reader#2]
Looks like `ExcelWorkbook.get_sheet_name_list()` is broken.

I think there is a `get_root()` missing, but it still crashes.

**Comment by whiteshampoo** [comment]
I think it should be like this:

`return Array(xml_data.get_root().get_first_node("sheets")...`

**Comment by LaoDie1** [comment]
Ok, I just updated part of the content, here we need to get the path of the sheet data according to the RID, now it has been added

**Comment by whiteshampoo** [comment]
wow, that was fast :D
seems to work fine now :)

Dont forget to update the "Download Commit/URL" in the Godot Asset Library
