### ISSUE TITLE
hi，大佬，excel文件在打包的时候会打包进pck文件吗？

### ISSUE THREAD

**Issue by Sasinim5** [LaoDie1/godot-excel-reader#6]
打包之后发现目录函数调用报错，目录文件为null

**Comment by LaoDie1** [comment]
需要在导出时的资源里添加 xlsx，才能打包进去

**Comment by LaoDie1** [comment]
![image](https://github.com/LaoDie1/godot-excel-reader/assets/34774872/b30529d6-1c1e-402d-bf14-5751d30cb967)
