### ISSUE TITLE
如何打包excel资源？

### ISSUE THREAD

**Issue by reoreo-zyt** [LaoDie1/godot-excel-reader#8]
我在打包过后通过自己复制一份数据可以正常拿到excel的数据。
![image](https://github.com/user-attachments/assets/dc29d597-9892-481e-bfb5-cfa559c95c8c)
但是配置的打包却不行，希望可以得到指点下。
![image](https://github.com/user-attachments/assets/a1e5e1e9-605c-46b2-9534-0310475dc249)
![image](https://github.com/user-attachments/assets/eaf8b404-e53f-4e56-882d-b213f0e13bb6)

**Comment by LaoDie1** [comment]
你换成“*.xlsx”试试。要不你下载最新的代码，使用 load 的数据试试
```
var excel_data = ExcelFileData.load_file(xlsx_path)
var table_data = excel_data.get_sheet_data("Sheet1")
print(JSON.stringify(table_data, "\t"))

```

**Comment by reoreo-zyt** [comment]
换成 *.xlsx 可以了，不知道为啥具名的方式不行。感谢
